### ISSUE TITLE
Bug: escape characters in ODI website's page titles

### ISSUE THREAD

**Issue by giacecco** [theodi/shared#511] opened 2015-01-27 17:12 UTC
![screen shot 2015-01-27 at 17 09 57](https://cloud.githubusercontent.com/assets/303693/5922966/b206ae60-a647-11e4-8c81-f50fc3c973fb.png)

**Comment by Floppy** [comment] 2015-02-23 14:13
Duplicate of #393

**Closed** 2015-02-23 14:16 UTC
Labels: 4 - Done, c: website
